# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='roger.proto',
  package='roger',
  serialized_pb=_b('\n\x0broger.proto\x12\x05roger\"O\n\x0b\x41\x63\x63\x65ssToken\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x0e\n\x06scopes\x18\x02 \x01(\x04\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x07\x12\x0b\n\x03ttl\x18\x04 \x01(\r\"2\n\x0cRefreshToken\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x0e\n\x06scopes\x18\x02 \x01(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACCESSTOKEN = _descriptor.Descriptor(
  name='AccessToken',
  full_name='roger.AccessToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='roger.AccessToken.account_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scopes', full_name='roger.AccessToken.scopes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='roger.AccessToken.created', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='roger.AccessToken.ttl', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=101,
)


_REFRESHTOKEN = _descriptor.Descriptor(
  name='RefreshToken',
  full_name='roger.RefreshToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='roger.RefreshToken.account_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scopes', full_name='roger.RefreshToken.scopes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['AccessToken'] = _ACCESSTOKEN
DESCRIPTOR.message_types_by_name['RefreshToken'] = _REFRESHTOKEN

AccessToken = _reflection.GeneratedProtocolMessageType('AccessToken', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSTOKEN,
  __module__ = 'roger_pb2'
  # @@protoc_insertion_point(class_scope:roger.AccessToken)
  ))
_sym_db.RegisterMessage(AccessToken)

RefreshToken = _reflection.GeneratedProtocolMessageType('RefreshToken', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHTOKEN,
  __module__ = 'roger_pb2'
  # @@protoc_insertion_point(class_scope:roger.RefreshToken)
  ))
_sym_db.RegisterMessage(RefreshToken)


# @@protoc_insertion_point(module_scope)
